name: Issue Management

on:
  issues:
    types: [opened, reopened]

env:
  AIS_PROJECT_URL: ${{ secrets.AIS_PROJECT_URL }}

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to AIS project
        if: env.AIS_PROJECT_URL != ''
        uses: actions/add-to-project@v0.3.0
        with:
          project-url: ${{ secrets.AIS_PROJECT_URL }}
          github-token: ${{ secrets.AIS_ADMIN_KEY }}

